<?php
$config = array();
$config['host'] = "localhost";
$config['user'] = "root";
$config['pwd'] = "";
$config['db'] = "api";
$config['currencies']=array(
		"1CR","42","365","888","A3C","AAA","ABY","AC","ACC","ADN","AIR","ALF","AMC","ANC","ARG","ATH","AUR","AV","AXIS","BANK","BBR","BC","BCAT","BCC","BCH","BCN","BCT","BCX","BDC","BDG","BELA","BEN","BET","BITS","BLC","BLU","BNS","BONES","BOST","BQC","BTB","BTCS","BTCX","BTE","BTG","BTL","BUK","BURN","BWC","C2","CACH","CAI","CAIX","CAP","CASH","CAT","CC","CCN","CDC","CESC","CFC","CGA","CGB","CHA","CHCC","CINNI","CLOAK","CLR","CMC","CNC","CNH","CNOTE","CNY","COIN2","COMM","COOL","CRC","CRT","CRYPT","CSC","CT","CTZ","CURE","CYC","DB","DCM","DEM","DGB","DGC","DIEM","DIG","DIS","DMD","DOGE","DOPE","DRK","DRM","DTC","DVC","DVK","EAC","EBT","EFL","ELC","ELT","EMC2","EMD","ENC","ENRG","ERC","EUR","EXC","EXE","EZC","FAC","FBC","FCN","FFC","FLAP","FLASH","FLT","FOX","FRAC","FRC","FRK","FRQ","FST","FTC","FUEL","FZ","GAC","GBP","GDC","GDN","GIAR","GIVE","GLB","GLC","GLD","GLX","GLYPH","GOAL","GOLD","GRC","GRK","GRN","GRS","H2O","H5C","HBN","HC","HIC","HIRO","HKC","HMY","HOT","HPY","HUC","HVC","HYPER","I0C","IFC","ISR","ITC","IVC","IXC","JKC","JPC","JUG","KDC","KGC","KIWI","KTK","LC","LCL","LEAF","LGC","LGD","LIMX","LK7","LKY","LOL","LOT","LTB","LTC","LTCX","LYC","MAMM","MARU","MAST","MAX","MEC","MEOW","METH","MHYC","MIL","MINT","MMC","MMXIV","MN1","MN2","MNC","MNS1","MON","MPL","MRC","MRS","MRY","MUGA","MUN","MYC","MYR","MZC","NAN","NAS","NAUT","NBL","NC2","NEC","NET","NHZ","NJA","NL","NLG","NMC","NOBL","NOTE","NRB","NRS","NTC","NTR","NVC","NXT","NYAN","OC","OLY","OPC","ORB","OSC","PAWN","PC","PER","PHS","PIGGY","PLC","PLX","PMC","PND","POT","PPC","PRC","PRT","PTC","PTS","PURE","PXC","PYC","POINTS","Q2C","QBC","QCN","QORA","QRK","QTM","RBY","RDD","REDD","RIC","ROM","RPC","RT2","RUR","RYC","SAT","SBC","SC","SFR","SHARE","SHIBE","SHOP","SLM","SLR","SMC","SNCX","SOC","SPA","SPC","SPT","SRC","SRG","START","STR","SUM","SUM2","SUN","SUPER","SXC","SYNC","TAC","TAG","TAK","TEK","TES","TGC","THC","TRC","UNB","UNO","UNVC","URO","USD","USDE","UTC","UVC","VMC","VOOT","VRC","VTC","WATER","WC","WDC","WEST","WIFI","WIKI","WIN","WOLF","X13","X13C","XBC","XC","XCP","XDG","XDQ","XHC","XJO","XLB","XLC","XMR","XPM","XRP","XSI","XSV","XVN","XXC","YAC","YACC","YANG","YBC","YC","YIN","YMC","ZCC","ZED","ZET","ZIP","ZS"
	);
?>